AMUL Stock checker script

diff --git a/.github/workflows/stock-check.yml b/.github/workflows/stock-check.yml
--- a/.github/workflows/stock-check.yml
+++ b/.github/workflows/stock-check.yml
@@ -31,5 +31,5 @@ jobs:
           PYTHONPATH: .
         run: |
           for i in 1 2 3 4 5; do
-            python stock_check.py && break || echo "Attempt $i failed, retrying in 10 seconds..." && sleep 10
+            python app/main.py && break || echo "Attempt $i failed, retrying in 10 seconds..." && sleep 10
           done
